### ISSUE TITLE
error when boost my server

### ISSUE THREAD

**Issue by ShockAnWave** [Masihdev1/Boost-Unboost-Announce#5]
![image](https://github.com/user-attachments/assets/11d754d0-1dc4-434f-b505-02633374d71f)

**Comment by CalledMasih** [comment]
Hello! Thank you for reporting this issue. When someone clicks the button, Discord sends a request to your bot. However, if your bot takes too long to respond (over **3** seconds), this common error can occur—even if the code itself is fine.

**Solution**:
Try clicking the button again or consider switching to a high-speed hosting service to improve response times.

**Comment by ShockAnWave** [comment]
> Hello! Thank you for reporting this issue. When someone clicks the button, Discord sends a request to your bot. However, if your bot takes too long to respond (over **3** seconds), this common error can occur—even if the code itself is fine.
> 
> **Solution**: Try clicking the button again or consider switching to a high-speed hosting service to improve response times.

ok thank you
